# Generated by Django 4.0.4 on 2022-05-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlescope_alter_scope_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleScope',
            new_name='ArticleTag',
        ),
        migrations.RenameModel(
            old_name='Scope',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
