# Generated by Django 4.0.4 on 2022-05-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_articlescope_articletag_rename_scope_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='scope',
            new_name='tag',
        ),
    ]
