# Generated by Django 4.0.4 on 2022-05-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_scope_articletag_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTag',
            new_name='Scope',
        ),
    ]
